### ISSUE TITLE
Neuro-Evolution with TensorFlow.js!

### ISSUE THREAD

**Issue by shiffman** [shiffman/Tensorflow-JS-Examples#7]
I'm working on a port of my [Neuro-Evolution Flappy Bird example](https://github.com/CodingTrain/Toy-Neural-Network-JS/tree/master/examples/neuroevolution-flappybird) to use TensorFlow.js. The non tf.js version of this is explained in a [5 part video series that starts here](https://youtu.be/c6y21FkaUqw). I'm hoping to revisit this with tf.js in a future video.

In the port, I'm using `tf.layers` to create the Neural Network and `model.getWeights()` and `model.setWeights()` to copy / mutate the model. However, I'm getting some strange behavior. @nsthorat @dsmilkov do you see a flaw in my methodology for copy/mutation? 

* [`copy()`](https://github.com/shiffman/Tensorflow-JS-Examples/blob/master/04_neuro_evolution/nn.js#L35)
* [`mutate()`](https://github.com/shiffman/Tensorflow-JS-Examples/blob/master/04_neuro_evolution/nn.js#L47)

I may just build the model tf operations instead of `tf.layers` to dig into this a bit more.

**Comment by nsthorat** [comment]
Hey Dan!

What kind of strange behavior are you seeing?

One thing I would note is you shouldn't override the value like this: https://github.com/shiffman/Tensorflow-JS-Examples/blob/master/04_neuro_evolution/nn.js#L55

Actually because of the way we're sharing these TypedArrays you're in place mutating the underlying values in the Tensor :/. One simple solution is to use arraySync instead of dataSync since we do a copy. Or you can copy the output of dataSync to a new Float32Array (using a new Float32Array and TypedArray.set).

**Comment by nsthorat** [comment]
BTW, if you use the arraySync route you have to deal with the dimensionality of weights, maybe use the second approach of copying the Float32Array output of the dataSync.

**Comment by shiffman** [comment]
Aha, this is the issue! (Big thanks to @meiamsome who also discovered this.) I didn't realize that `dataSync()` doesn't copy the data! So I was shallow instead of deep copying and the new population was sharing weights across models!  An extra `slice()` function to copy sorts out the issue.

```javascript
let arr = w[i].dataSync().slice();
```

More soon!

**Comment by nsthorat** [comment]
Yeah actually we should probably do this in the library, I'll send a fix but for now just slice it (slice is shallow so is cheap) :)

**Comment by nsthorat** [comment]
FYI, we decided not to do this in the library. TypedArray.slice() is shallow but in JS that's not a lazy copy, it will copy all the numbers to the new array slowing down dataSync(). I'm going to clarify this in documentation, but unfortunately we're not going to make the change upstream so you'll have to slice the TypedArray in your code.

**Comment by shiffman** [comment]
No worries, I appreciate all the info and help! Having this handled by tf.js is by no means necessary for what I'm working on.

**Comment by shiffman** [comment]
Closing as the example is working great now! More to come...

**Comment by parweb** [comment]
Well thank you, I find this conversation after torturing my natural neural brain for the entire afternoon.
exactly what need !

By the way the repository location code of @shiffman change

https://github.com/shiffman/Tensorflow-JS-Examples/blob/master/04_neuro_evolution_flappy/nn.js
